### ISSUE TITLE
Allow usage of global ProcessApplication listeners with @EnableProcessApplication

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#184]
see https://forum.camunda.org/t/preferred-way-to-use-process-application-event-listener/2238/3

idea: have certain listeners marked by qualifier injected in the SpringBootProcessApplication

**Comment by falko** [comment]
Is there a chance to release milestone 2.2.0 without this, so that users can start to work with Camunda 7.7?

**Comment by jangalinski** [comment]
its built already, Svetlana just had a problem pushing it on friday ...

**Comment by saroff** [comment]
I don't see how these commits solves the problem, it adds the way to provide "PostDeploy" and "PreUndeploy" callbacks, but i can't find a way to provide global Execution and Task listeners.

**Comment by falko** [comment]
@jangalinski: I agree with @saroff and therefore reopen this issue. How can one use [Process Application Event Listeners](https://docs.camunda.org/manual/latest/user-guide/process-applications/process-application-event-listeners/) with Spring Boot and @EnableProcessApplication?

**Comment by falko** [comment]
@sdorokhova any opinion?

**Comment by sdorokhova** [comment]
Hi @falko and everybody,
you're right: commits linked above does not implement global task and execution listeners for process application in context of Spring Boot. This was some misunderstanding.

Some time ago @jangalinski created a [JIRA issue](https://app.camunda.com/jira/browse/CAM-8965)  for the feature and a [PR](https://github.com/camunda/camunda-bpm-spring-boot-starter/pull/298/commits/385eb452b761de2354695706b64c74106c1e6ecf), which is not finished yet. @jangalinski , do you have any news on this? Are you may be planning to look at it once again? 😉 

I will close this issue, as we track Camunda Spring Boot related issues in JIRA now. Feel free to share your thoughts on the subject there.
