### ISSUE TITLE
update spring boot 1.5.2

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#203]

**Comment by jangalinski** [comment]
this currently fails!

**Comment by stsymbal** [comment]
Hi Jan,

What features are not working with Spring Boot 1.5.1? What about 1.5.2?

Thanks,
Sergii

**Comment by jangalinski** [comment]
When I switch to 1.5.2.RELEASE and do a `mvn clean install`, I get  13 test errors due to `IllegalState Failed to load application context`.

This seems to be caused by: `.NoClassDefFoundError: org/hibernate/HibernateException`


Tests in error:

```
  CamundaAutoConfigurationIT.autoDeploymentTest » IllegalState Failed to load Ap...
  CamundaAutoConfigurationIT.jobConfigurationTest » IllegalState Failed to load ...
  CamundaAutoConfigurationIT.orderedConfigurationTest » IllegalState Failed to l...
  CamundaBpmActuatorConfigurationIT.jobExecutorHealthIndicatorTest » IllegalState
  CamundaBpmActuatorConfigurationIT.processEngineHealthIndicatorTest » IllegalState
  CamundaBpmAutoConfigurationIT.ensureProcessEngineServicesAreExposedAsBeans » IllegalState
  CamundaJobExecutionAutoConfigurationIT.jobConfigurationTest » IllegalState Fai...
  CamundaJpaAutoConfigurationIT.jpaTest » IllegalState Failed to load Applicatio...
  CamundaJpaAutoConfigurationIT.transactionTest » IllegalState Failed to load Ap...
  CamundaNoJobExecutionAutoConfigurationIT.jobConfigurationTest » IllegalState F...
  CamundaNoJpaAutoConfigurationIT.jpaDisabledTest » IllegalState Failed to load ...
  CamundaNoJpaAutoConfigurationIT.pojoTest » IllegalState Failed to load Applica...
  HistoryLevelDeterminatorJdbcTemplateImplIT.test » IllegalState Failed to load ...
```

examplary stacktrace:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManagerFactoryBuilder' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Unsatisfied dependency expressed through method 'entityManagerFactoryBuilder' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaVendorAdapter' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.JpaVendorAdapter]: Factory method 'jpaVendorAdapter' threw exception; nested exception is java.lang.NoClassDefFoundError: org/hibernate/HibernateException

```

**Comment by jangalinski** [comment]
Update: I checked the dependency:tree and it really is the case that 

https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/HibernateException.html

was removed from hibernate-core when they went from 5.0.11 to 5.0.12

ideas?

**Comment by jangalinski** [comment]
OK, forget my last comment ... seems I had local problems while updating hibernate ...

**Comment by jangalinski** [comment]
OK, next problem ... camunda-bpm-assert uses a very outdated assertj-core version, spring-boot-starter-test increased to 2.6.0 and now bpm-assert can not be used for tests anymore ... see also #164

**Comment by jangalinski** [comment]
I solved this by copying the bpm-assert classes to the starter-test. This is not optimal, but bpm-assert uses a way outdated assertj version.
